engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 50
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
    checks:
      Controversial/CamelCaseClassName:
        enabled: false      # because jQuery.php and similar class names
      Controversial/CamelCasePropertyName:
        enabled: false      # becasue we use _xx for private properties (that must remain public)
      Controversial/CamelCaseMethodName:
        enabled: false      # methods start with _xx for private methods (that must remain public)
  radon:
    enabled: true
ratings:
  paths:
  - "src/**"
exclude_paths:
- "docs/**"
- "tests/**"
- "vendor/**"
