language: php

os:
    - linux

php:
    - '7.2'
    - '7.3'

services:
    - mysql
    - xvfb

env:
  global:
    - SELENIUM_MAJ_VER=3.141
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.59
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - CHROME_DRIVER_VER=2.44

addons:
  apt:
    update: true
    chrome: stable

before_install:
    - npm get prefix
    - npm install -g less less-plugin-clean-css uglify-js

install:
      #- export DISPLAY=':99'
  - Xvfb :99 -screen 0 1280x1024x16 +extension RANDR > /dev/null 2>&1 &

before_script:
    # prepare dir for coverage
    - mkdir -p coverage
    - chmod 777 coverage
    # Setup selenium
    - wget  https://selenium-release.storage.googleapis.com/${SELENIUM_MAJ_VER}/${SELENIUM_JAR}
    - java -jar ${SELENIUM_JAR} > /dev/null 2>&1 &

    # Setup chromedriver
    - wget http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VER}/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

    - php -S localhost:8888 > /dev/null 2>&1&
    - mysql -e 'create database atk4;'
    - mysql atk4 < demos/atk4.sql
    - mv demos/db.travis.php demos/db.php
    - (cd js; npm install --loglevel=error; npm run build)
    - lessc public/agileui.less public/agileui.css  --clean-css="--s1 --advanced --compatibility=ie8" --source-map
    - uglifyjs --compress -- public/agileui.js > public/agileui.min.js
    - composer install --no-progress --no-suggest --prefer-dist

script:
    - ./vendor/phpunit/phpunit/phpunit --no-coverage
    - bash tools/test.sh

cache:
  directories:
    - $HOME/.composer/cache

