version: "1.0"
stages:
  - clone
  - build
  - push
  - deploy
steps:
  main_clone:
    type: git-clone
    stage: clone
    repo: atk4/ui
    revision: "${{CF_BRANCH}}"

  fix_sha:
    stage: clone
    title: Inject dependency SHA to bypass cache
    commands:
      - ./tools/inject-dependency-sha.sh

  build:
    type: build
    stage: build
    image_name: atk4/ui-demo
    dockerfile: demos/Dockerfile
  push:
    type: push
    stage: push
    image_name: atk4/ui-demo
    registry: atk4
    candidate: "${{build}}"
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "${{CF_REVISION}}"
  deploy:
    image: codefresh/kubectl:1.13.3
    stage: deploy
    commands:
      - echo $CF_KUBECONFIG_PATH
      - kubectl config use-context atk
      - kubectl -n atk-demo set image deployment/atk-demo atk-demo="atk4/ui-demo:${{CF_REVISION}}"

