name: Build Release

on:
  push:
    branches:
      - '*.build'
      - 'release/*'

jobs:
  autocommit:
    name: Build Release
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install PHP dependencies
        run: composer update --ansi --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Composer unset version
        run: composer config version --unset

      - name: Update composer.json
        run: >-
          php -r '
          $f = __DIR__ . "/composer.json";
          $data = json_decode(file_get_contents($f), true);
          foreach ($data as $k => $v) {
              if (preg_match("~^(.+)-release$~", $k, $matches)) {
                  $data[$matches[1]] = $data[$k]; unset($data[$k]);
              }
          }
          $str = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n";
          echo $str;
          file_put_contents($f, $str);
          '

      - name: Composer validate config
        run: composer validate --strict --no-check-lock && composer normalize --dry-run --no-check-lock


# TODO
      - uses: actions/checkout@master
      - name: Update CDN destination
        shell: bash
        run: |
          v=$(echo ${{ github.ref }} | cut -d / -f 4)
          echo "::set-env name=version::$v"

          git branch
          #sed -i "s|'https://raw.githack.com/atk4/ui/develop/public.*|'https://cdn.jsdelivr.net/gh/atk4/ui@$v/public',|" src/App.php
          # it was develop, it can stay develop for DEVELOP branch, so we see changes to JS right away.

          # Set next version for develop branch
          a=( ${v//./ } )
          nv=${a[0]}"."$(( ${a[1]} +1 ))".0-BETA"
          sed -i "s|public \$version.*|public \$version = '$nv';|" src/App.php
          git config --global user.email "bundler@agiletoolkit.org"
          git config --global user.name "Release Bundler"
          git commit -am "Update versions for develop"

# TODO

      - name: Compile JS files for CDN
        shell: bash
        run: |

          # Update version for the release branch
          v=$(echo ${{ github.ref }} | cut -d / -f 4)
          sed -i "s|public \$version.*|public \$version = '$v.0';|" src/App.php
          npm install -g less-plugin-clean-css
          (cd js; npm ci; npm run build; cd ..)
          lessc public/agileui.less public/agileui.css --clean-css="--s1 --advanced" --source-map
          echo '!agileui.css.map' >> public/.gitignore
          git add public
          git config --global user.email "bundler@agiletoolkit.org"
          git config --global user.name "Release Bundler"
          git commit -am "Releasing $v.0"
          echo "If everything is good and CI/CD pass - please manually create tag $v.0 on this commit ^^"


      - name: Commit
        run: |
          git config --global user.name "$(git show -s --format='%an')"
          git config --global user.email "$(git show -s --format='%ae')"
          git add -A && git diff --staged && git commit -m "Build Release"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}.gen
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
