name: Test Release Drafter

on:
  push:
    branches:
      - test-release-drafter

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile JS files for CDN
        run: |
          npm install -g less-plugin-clean-css
          (cd js; npm install; npm run build; cd ..)
          lessc public/agileui.less public/agileui.css --clean-css="--s1 --advanced" --source-map
          echo '!agileui.css.map' >> public/.gitignore
          git add public
